/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEdge: typeof import('./src/components/flow/AddEdge.vue')['default']
    AddNodeButton: typeof import('./src/components/flow/AddNodeButton.vue')['default']
    BusinessHoursEditor: typeof import('./src/components/flow/drawer/BusinessHoursEditor.vue')['default']
    CommentEditor: typeof import('./src/components/flow/drawer/CommentEditor.vue')['default']
    ConnectorNode: typeof import('./src/components/flow/ConnectorNode.vue')['default']
    CreateNodeModal: typeof import('./src/components/flow/CreateNodeModal.vue')['default']
    FlowCanvas: typeof import('./src/components/flow/FlowCanvas.vue')['default']
    LeafAddButton: typeof import('./src/components/flow/LeafAddButton.vue')['default']
    NodeDrawer: typeof import('./src/components/flow/drawer/NodeDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMessageEditor: typeof import('./src/components/flow/drawer/SendMessageEditor.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputTime: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WorkflowNode: typeof import('./src/components/flow/WorkflowNode.vue')['default']
  }
}
